# Knowledge Gaps Limiting Robust, Scalable and Credible NbCS for the United States {#sec-knowledge}

## Knowledge gaps related to field data scarcity {#sec-data-scarcity}

Our understanding of the technical mitigation potential of many NbCS strategies is limited by a scarcity of representative field data, either because these data do not yet exist or because they are not yet freely accessible. Notable exceptions exist, including networks of ecosystem-scale flux towers (e.g., AmeriFlux65,66 and NSF’s National Ecological Observatory Network, or NEON67) and the wealth of information on tree biomass and associated stand dynamics supported by the USDA Forest Service Forest Inventory and Analysis (FIA) program68. These networks may provide sufficiently representative data to map carbon fluxes at coarse scales69, or even to estimate potential changes in plant carbon stocks achievable with some NbCS like reforestation70,71. However, networks like NEON, FIA and AmeriFlux were not designed specifically with the goal of evaluating NbCS, and many specific NbCS management strategies (e.g., cover crops, soil amendments, altered forest management, wetland restoration) are potentially un- or under-represented in these networks. These networks were also not designed to be interoperable, which makes it difficult to blend information from disparate networks (e.g., FIA and AmeriFlux) into synthetic analyses and products. Efforts to dynamically catalog existing NbCS field trials and the activities of relevant monitoring networks would permit an informed prioritization of new data collection and facilitate synthesis of new and existing network data.

Particularly in agricultural systems, there is a lack of scientific consensus about the degree to which NbCS practices can sequester sufficient atmospheric carbon to help mitigate climate change72-75. This disagreement stems in part from a **large degree of uncertainty surrounding the spatial and temporal patterns of soil organic carbon (SOC) and net GHGs across agricultural landscapes76-80**. Field trials for emerging NbCS strategies (e.g., enhanced rock weathering) are scarce. However, there is even a lack of representative soil carbon storage data for a practice like cover cropping, which has long been known to confer multiple environmental benefits for soil health and water quality81-83. One of the most widely cited papers reporting on the soil carbon benefits of cover crops34 is informed by data from 37 sites globally, with only 10 locations within the United States. Likewise, although no-till management has long been lauded for its benefits to soil health and for its role in reducing on-farm fossil fuel emissions, the ability of no-till management to sequester atmospheric carbon has been hotly debated in the scientific literature72,84. Some studies conclude it has no potential to mitigate climate change, whereas other research suggests that mitigation potential depends on climate and soil texture85. Almost no data exists on the impact of multiple, or stacked, NbCS farming practices despite the widespread use of stacking among regenerative farmers. More data is needed from a much more representative set of ecosystems to quantify where these practices succeed as climate solutions, alone and in combination.

**The mechanisms by which agricultural practices impact coupled carbon and nitrogen dynamics is another major knowledge gap.** Understanding the net GHG impact of agricultural management demands data on how specific practices impact both soil organic carbon (SOC) and associated GHGs like nitrous oxide and methane. Agricultural practices that build SOC can result in increased nitrous oxide emissions, which could potentially offset gains in SOC sequestration86,87. Quantifying potential trade-offs is difficult because nitrous oxide emissions vary temporally and spatially and constitute a highly uncertain component of agricultural GHG budgets87. In addition, practices which may reduce N2O from fertilizer or manure application may adversely affect other parts of the nitrogen cycle and increase ammonia loss88. **We need increased data coverage over time and space to more accurately quantify the net GHG impacts and additional positive or negative effects of agricultural management practices.** These databases could build onto and complement USDA Agricultural Research Service GHG synthesis projects such as TRAGNET89 and GRACEnet90,91. 

Our understanding of NbCS potentials in agricultural landscapes moreover requires data from working farms. Much of our knowledge about management impacts on SOC sequestration comes from long-term agricultural field trials designed to minimize inherent variability in soils and landscape position that exists in the real-world92. Thus, estimates of SOC sequestration rates are often greater than those measured at the farm scale93, and practices as implemented in 2. Knowledge Gaps Limiting Robust, Scalable and Credible NbCS for the United States 10  research trials (e.g., long-term no-tillage) might not reflect how these practices are implemented in practice by farmers (e.g., intermittent tillage). A network of sites (ideally containing paired fields evaluating different practices) that collect data on management records, soil properties, climate data, crop yields, carbon fluxes, and nitrogen fluxes could help build external validity of agricultural management impacts on net GHG outcomes. 

Many of these field data limitations also apply to terrestrial wetland ecosystems, which have additional, unique knowledge gaps. There is still a need to better map wetlands94 and to locate restoration and conversion avoidance opportunities more precisely. Next, emissions and carbon trajectories associated with different wetland conditions and restoration strategies need to be rigorously quantified. The use of eddy covariance combined with long-term, plot-level measurements of GHG emissions are important tools to fill this gap95, though wetlands are relatively underrepresented in networks like AmeriFlux and NEON96. Wetlands also pose measurement difficulties as they are a mosaic of water and vegetation with stark gradients in nutrients, plant species, soil saturation and salinity (for estuaries) that can impact carbon cycling and GHG emissions97-99. Getting the fluxes right at the field-scale requires a mix of measurement and gap-filling approaches and high-resolution remote sensing100,101. It is also important to consider socioeconomic factors, including the design of locally appropriate incentive programs that account for competing land uses and the multiple ecosystem services102,103, plus impacts associated with disturbance104. 

Especially in wetland environments and the tile-drained croplands that predominate the Corn Belt, more information is required regarding potentially significant leakage through lateral transport of dissolved and particulate carbon105-107. A change in SOC may represent an increase in carbon sequestration from the atmosphere, but it may also represent a decrease in carbon losses through runoff and leaching. Depending on the fate of carbon exported in this way, an increase in soil carbon may not represent atmospheric CO2 sequestration of the same magnitude. Unfortunately, information about lateral export of carbon, especially in places where carbon pools and fluxes are already being measured, is scarce and largely unaggregated into network databases.  

Field data on the carbon contained in forests are relatively more plentiful, due in large part to the FIA program. Indeed, FIA data have played a central role in governing our understanding of the dynamics of carbon stored in tree biomass, and FIA biomass data are featured in most attempts to quantify the mitigation potential of reforestation in the U.S.31,70,108-110. However, FIA was not designed explicitly for the purpose of documenting how a limited set of management strategies will alter the GHG flux balance of America’s forests. For example, while SOC has been measured on a subset of FIA plots111, **data on ___changes in soil carbon___ are not yet available from FIA.** Moreover, the FIA network is characterized by long resampling intervals (5-10 years) and protocols that lack rigorous documentation of the causes of tree mortality or regeneration of young trees. These limitations make it difficult to disentangle the influence of multiple drivers of forest carbon dynamics that act simultaneously, including climate variability and change, natural disturbances, forest harvest, the CO2 fertilization effect, and their interactions. Furthermore, **whether distributed plot networks like FIA adequately capture the carbon cycle impacts of patchy disturbances, particularly fire and beetle outbreaks, is also a major unknown.**

::: {.callout-important}
## Box 2.1: Knowledge gaps related to data scarcity 

**Gap 2.1a:** Many categories of NbCS are under-represented in existing networks, and field trial data are scarce. 

**Gap 2.1b:** The absence of long-term monitoring data on soil carbon in agricultural working lands limits consensus on when and where many NbCS are most likely to succeed. 

**Gap 2.1c:** Unrepresentative data on coupled soil carbon and nitrogen dynamics, and lateral carbon transport, limits evaluation of inherent tradeoffs (e.g. carbon versus methane and nitrous oxide, sequestration versus runoff). 

**Gap 2.1d:** The design of existing forest inventory programs limits understanding of carbon stored in soils, litter, and dead wood, and precludes attribution of tree growth and mortality to disturbances and management. In addition, some disturbance such as wildfire may be incompletely captured with a distributed plot sampling network.
:::

## Knowledge gaps related to a historic emphasis on a limited set of carbon stocks {#sec-carbon}

Even if data are plentiful, substantial additional uncertainty can be traced to a historic emphasis on two slowly evolving carbon stocks (or pools); specifically, [1] soil carbon in the top 30 cm of the soil in croplands and grasslands, and [2] and the carbon contained in aboveground plant biomass. Approaches for estimating the carbon contained in a soil sample, or in a single tree, are well established. In the case of soil carbon, small soil cores are physically extracted from the soil and analyzed for their carbon content in the laboratory. For tree carbon, field measurements of tree diameter and height are collected and used as inputs into empirical (allometric) relationships that describe species-specific relationships between tree size and carbon content. While the accessibility of these measurements is advantageous, linking the mitigation potential of NbCS solely to present-day changes in these pools remains limited in three major ways. 

First, a narrow focus on only two pools misses important carbon sources and sinks and prevents ecosystem-scale assessments of NbCS impacts7,112,113 (Fig. 3). Soils store a large proportion of carbon in the sub-surface (depths > 30 cm). Yet research on soils has focused on the surface (0-30 cm) as the zone of greatest biological activity that responds most readily to management, and nearly all crediting systems only model or measure down to 30 cm or less55,114. Studies that have captured greater depths reveal that certain practices like no-till farming result in a redistribution of SOC such that perceived gains in surface soils may be attenuated by losses at depth84,115,116. The lack of data on SOC dynamics at depth hinders our ability to draw robust conclusions and uncertainty remains high117-119.  

In the case of tree carbon, allometric relationships linking tree size and carbon content are typically based on trees that were harvested decades ago. Thus, these allometric models may not incorporate the many ways that climate feedbacks like rising atmospheric CO2 and increasing drought stress can affect patterns of tree growth and allocation120-121. Moreover, while tree biomass is often the fastest-growing pool of carbon in forests, forest soil carbon is a dynamic pool in which most forest carbon resides123. A non-negligible quantity of carbon assimilated by trees is ultimately translocated to and stored in the soil each year through root exudates, leaf litter, and inputs from downed woody debris122. Moreover, in a world characterized by more frequent tree die-offs, the rates of accumulation in standing and downed dead biomass carbon stocks could increase. Indeed, over the past 10 years, the downed wood biomass of forests in the contiguous U.S. has increased 18% while live biomass has increased only 4%123. Finally, a growing body of literature suggests that the link between stem biomass increment and tree carbon uptake (e.g., net primary productivity) is not particularly strong124126. Taken together, these considerations motivate forest NbCS assessment and accounting protocols that consider ecosystem-scale fluxes and a larger set of carbon pools.  

Second, because ecosystem carbon pools are quite large to begin with, it can take years for a change in these pools to become detectable, whereas a change in the land-atmosphere flux can be detected immediately. To understand this limitation, it can be helpful to visualize a swimming pool, representing all the carbon in an ecosystem. Imagine the pool is being filled by a hose (representing the net flux of CO2 from the atmosphere to the ecosystem), and that there is negligible outflow from the pool (e.g., leaks like the lateral loss of carbon through runoff are small). If the hose inflow rate is doubled (representing the implementation of an NbCS strategy), an observer tracking inflow from hose will be able to quantify the impact of the intervention immediately. However, an observer attempting to infer this flux by tracking changes in the volume of water in the pool will have to wait much longer for the change in inflow to become detectable. Most NbCS accounting and crediting protocols are focusing on the pool, and not the hose. This mismatch has important consequences for the speed with which the climate benefits of individual projects can be quantified. A multiyear delay in understanding if an NbCS treatment is producing the desired outcomes increases uncertainty in implementation programs and limits our ability to rapidly evaluate the effectiveness of emerging NbCS strategies. 

Together, these first two issues point to advantages and disadvantages of both flux and stock measurement and detection techniques (Fig. 3). In isolation, ecosystem-atmosphere flux observations are unable to track where carbon is stored in an ecosystem (an important determinant of durability) or the potential for rapid off-site release of recently sequestered CO2 (e.g., following harvest or lateral export in runoff). Stock change measurements can be ambiguous regarding where carbon comes from and goes to, and may not differentiate between increases in inputs or decreases in outputs. For example, an increase in soil carbon might result from increased litter production because of stimulated plant growth, which would cause a reduction in atmospheric CO2, or from enhanced litter production due to disturbance, which would not lower CO 2 concentrations. Both stock and flux approaches are incomplete without the other. We need confident tracking of carbon fluxes and stock changes with holistic tracing of carbon flows throughout the system. 

![Flux towers provide ecosystem-scale measurements of the net ecosystem exchange of CO2 between the land and the atmosphere, and some towers can also measure the land-atmosphere flux of methane and nitrous oxide. Because towers record information continuously, they can landsome atmosphere flux of methane and nitrous oxide. Because towers record information continuously, they can quickly detect the impact of changes in land cover and management, especially when deployed in an experimental setting. Their ability to continuously measure ecosystem-scale water and energy fluxes also makes them particularly useful for understanding biosphysical impacts. However, flux towers are not able to monitor carbon lost to harvest or runoff, and provide little information about the allocation of sequestered carbon to different pools. On the other hand, changes in ecosystem stocks will reflect the combined influence of inputs (e.g., sequestration/emission) and outputs (e.g., harvest/runoff) on pool sizes. Depending on how many pools are monitored, theses observations also provide more granular information about how sequestered carbon is allocated (e.g., to above versus belowground pools, including more stable versus more unstable forms of SOC). For these reasons, flux and stock measurements are best viewed as complimentary. The table in the lower left illustrates the relative advantages and disadvantages of each approach. Green symbols indicate an advantage, red symbols indicate a disadvantage, and yellow symbols indicate that the relative design. Image copyright William Scavone. All rights reserved.](/img/03-ecosystem-fluxes-stocks.jpg "Title: An illustration of key ecosystem fluxes (arrows) and stocks (or pools, white text)."){fig-alt="An Info Graphic of Key Ecosystem Fluxes and Stocks." #fig-key-fluxes-stocks}

Third, focusing on carbon stocks alone prevents a more holistic understanding of the overall GHG emission benefits (or unintended consequences) of a given NbCS strategy. Specifically, carbon stock changes are insufficient to understand NbCS impacts on emissions of non-CO2 GHGs like methane and nitrous oxide, which are particularly important to consider in wetlands and many agricultural systems. We urgently need strategies to resolve NbCS-driven changes to these GHGs with a precision that overcomes uncertainty due to natural variability.

::: {.callout-important}
## Box 2.2: Knowledge gaps related to a historic emphasis on a limited set of carbon stocks

**Gap 2.2a:** NbCS assessments and protocols lack ecosystem-scale perspectives that integrate over all relevant carbon sources and sinks.

**Gap 2.2b:** Limited ability to quickly quantify the actual benefit of NbCS on the ground.

**Gap 2.2c:** Limited undrestanding of NbCS impacts on methane and nitrous oxide emissions.
:::

## Knowledge gaps preventing policy-relevant mapping of NbCS mitigation potentials {#sec-mapping}

The potential climate benefits of a given NbCS strategy will vary from one location to the next, reflecting differences in climate, underlying soils, topography, and historic management regime. If the goal is to incentivize NbCS to maximize their climate benefits, the most robust NbCS implementation programs would be designed with an understanding of where and when a given strategy is most likely to succeed and would avoid allocating resources to interventions that do not offer tangible climate benefits. Unfortunately, spatially explicit maps of climate change mitigation benefits for most NbCS strategies are scarce. This is especially true for agricultural and wetland NbCS. At the time of this writing, to our knowledge, there are no published maps that rigorously describe the carbon uptake benefits, or biophysical impacts, of cover crops across the Corn Belt. Overall, a major factor limiting our ability to map the climate benefits of agricultural and wetland NbCS is a lack of representative data that spans many axes of variability (e.g., soils, climate, species, historic management, land ownership history).

There are a couple of exceptions. No-till agriculture has been widely studied through paired plot experiments, motivating several meta-analyses that incorporate field data into models that relate changes in soil carbon to mappable environmental drivers, yielding spatially explicit estimates of carbon sequestration potential127,128. However, recent work reveals that the change in soil carbon under no-till management varies as a function of both time and depth into the soil; and efforts to extrapolate estimates of the change in soil carbon to regional- and continental-scale may lead to misleading conclusions116. Likewise, mitigation potential maps of forest-based strategies – and especially reforestation – are relatively abundant. Data on aboveground biomass provided by inventory networks like FIA are fairly complementary with remotely-sensed proxies for forest biomass (e.g. from GEDI129) as well as a suite of existing models and carbon monitoring frameworks130,131 that predict carbon uptake based largely on changes in biomass. Nonetheless, mitigation potential maps will only be as robust as the underlying data; if these maps are informed primarily by changes in carbon stored in shallow soils and/or aboveground woody biomass, they will suffer from the same limitations described in the preceding section.

The spatial resolution of mitigation potential maps will ultimately be determined by the representativeness of the ground data used to train the scaling algorithms, and the resolution of the remote sensing products and models used for extrapolation. Maps at a resolution that matches the scale of individual farms and forest stands are likely infeasible in the near term. However, maps made at relatively fine scales (e.g. county-scale) may be possible for some NbCS strategies.

::: {.callout-important}
## Box 2.3: Knowledge gaps preventing policy-relevant mapping of NbCS mitigation potentials

**Gap 2.3a:** Especially in agricultural and wetland systems, we lack spatially-resolved maps of NbCS mitigation potentials, preventing an understanding of when and where these strategies are most likely to succeed. This gap is linked to a scarcity of representative ecological and socio-economic data.

**Gap 2.3b:** In forests, existing potential maps are primarily informed by data on tree biomass change, which miss other important carbon pools.
:::

## Knowledge gaps preventing a holistic assessment of NbCS biophysical impacts {#sec-holistic}

Any intervention designed to affect carbon cycling will have a concomitant impact on water and energy cycling (hereafter “biophysical impacts”), as these three cycles are closely coupled132. For example, due to the link between photosynthetic capacity and stomatal conductance133, greater ecosystem photosynthesis is typically associated with greater evapotranspiration46. All else being equal, an increase in evapotranspiration is likely to decrease soil moisture and runoff. Whether this is a favorable outcome greatly depends on the local climate regime, time of year, and management goals. For example, greater springtime evapotranspiration (e.g., linked to cover crop use) may be welcomed by producers throughout much of the Corn Belt, where saturated conditions can delay or even prevent planting of cash crop seeds134. Conversely, when and where soil moisture deficits are common and limit agro-ecosystem productivity, alterations to the hydrologic cycle that further deplete soil moisture would be undesirable. With some exceptions46,135,136, systematic frameworks for understanding how NbCS impact carbon and water cycles are rare, and more holistic assessments of coupled carbon-water impacts of NbCS are urgently needed. This is also critical for ensuring water management strategies are consistent and complementary with climate mitigation efforts, especially as water availability becomes less predictable.

Land cover and management shifts also affect energy budgets in ways that can impact temperature directly137. For example, replacing relatively light colored (high albedo) grasslands with darker (low albedo) forests will increase solar radiation absorbed at the surface, which can have a local warming effect. However, at the same time, forests tend to use more water (higher evapotranspiration) and generate more effective transport of heat energy away from the land surface (increased sensible heat flux). Both mechanisms tend to cause surface cooling at local scales138,139.

Arguably, for some categories of NbCS, our understanding of local temperature impacts is more advanced than our understanding of carbon cycle impacts. While no remote sensing platform is yet capable of sensing the net carbon flux directly, satellite estimates of land surface temperature and surface albedo have been widely available for decades. Moreover, flux towers measure all the relevant terms of the ecosystem energy budget. When deployed in a paired-site setting139,140, flux towers can tell us not only how local surface temperature is affected by a land cover or management shift, but also which underlying mechanisms are responsible for the shift138,139,141,142 Collectively, these data products have been widely used to demonstrate that NbCS strategies in some regions have an overall local surface cooling effect (e.g., tropical and temperate zone reforestation135,143,144; wetland restoration145, and conversion to frequently flooded agriculture lands146). In other cases (e.g., semi-arid and boreal forests), the radiative impacts of NbCS may lead to additional warming141,147. Nonetheless, the consequences for local surface temperature have not been rigorously quantified for many categories of NbCS. For all NbCS strategies, more work is necessary to understand the relationship between local surface and air temperature impacts148,149, especially during climate extremes like heat waves150,151.

Importantly, local temperature responses to NbCS do not necessarily scale up to regional or global temperature changes. In isolation, a decrease in albedo will tend to cause both local and global warming. To the extent that NbCS increase evapotranspiration that results in increased cloudiness, they may cause reductions in planetary albedo which has a cooling effect137. But on the other hand, heat diverted from the surface through enhancements to evapotranspiration and sensible heat flux is re-released in the atmosphere and does not escape the planetary climate system. Consequently, changes in local surface temperature are not necessarily correlated with a global climate system response, making changes in local surface temperature an incomplete indicator of the biophysical impacts of NbCS131,152,153. Although these mechanisms are broadly understood by meteorologists and climate scientists, they are not always considered by practitioners or even some scientists working with NbCS.

Finally, evidence from modeling studies suggests that modifications to energy and water cycling in one location can have downstream effects on water and energy cycling in other locations through non-local effects and so-called “eco-climatic teleconnections”154,155. Right now, our understanding of these non-local effects is limited to what we can learn from climate models, which often struggle to characterize resulting temperature changes with sufficient precision to match the scale of NbCS interventions.

::: {.callout-important}
## Box 2.4: Knowledge gaps related to biophysical impacts

**Gap 2.4a:** We lack a comprehensive framework for understanding how NbCS impact local water cycling.

**Gap 2.4b:** For most categories of NbCS, we lack a rigorous quantification of biophysical impacts for surface and air temperature at local to planetary scales.

**Gap 2.4c:** Climate and land surface models struggle to reproduce the direct temperature impacts of NbCS with enough precision to quantify local and non-local biophysical impacts.
:::

## Knowledge gaps limiting predictions of durability and disturbance risk {#sec-durable}

### The importance of durability for robust NbCS {#sec-robust-ncbs}

Durability refers to the period of time over which carbon removals or avoided emissions that result from an NbCS intervention persist without failure. The term is used in practice to characterize the duration for which carbon mitigation from a particular policy, market, or program is assured to remain out of the atmosphere. Durability depends on relevant physical and ecological risk factors that can lead to “reversals” through which carbon or other GHGs return to the atmosphere. For example, carbon stored in forests is vulnerable to mortality events driven by wildfire, drought, disease, and insects156. In many instances, durability also depends significantly on program governance features50, such as whether a parcel of land has committed to maintain climate-smart practices by contract or by easement, as well as whether a program includes insurance mechanisms to address reversal risks157. As a result, properly characterizing the durability of NbCS requires insights from natural and social sciences, as well as assessments of environmental economics and policy.