project:
  type: book
  output-dir: docs

book:
  title: "The science needed for robust,  scalable, and credible  nature-based climate solutions  for the United States: Full Report"
  author: "Kim Novick, et al."
  date: "10/12/2022"
  chapters:
    - index.qmd
    - overview-and-objectives.qmd
    - knowledge-gaps.qmd
    - bibliography.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



