project:
  type: book
  output-dir: docs

book:
  title: "The science needed for robust, scalable, and credible nature-based climate solutions in the United States"
  subtitle: Full Report
  description: An example IUB Libraries Scholarly Communication Deparment Published Report
  doi: "10.5967/n7r9-7j83"
  author: 
    - name: 
        given: Kim
        family: Novick
        literal: Kim Novick
      affiliations:
        - name: Indiana University Bloomington 
          department: Paul H. O'Neill School of Public and Environmental Affairs
          address: 107 S. Indiana Avenue
          city: Bloomington
          region: IN
          postal-code: 47405
          url: https://www.indiana.edu/
      url: https://oneill.indiana.edu/faculty-research/directory/profiles/faculty/full-time/novick-kimberly.html
      email: amazel@iu.edu
      orcid: 0000-0001-7241-0891
    - name:
        given: Christopher
        family: Williams
        literal: Christopher Williams
      affiliations:
        - name: Clark University
          department: Geography
          address: Jefferson 208
          city: Worcester
          region: MA
          postal-code: 01610-1477
          url: https://www.clarku.edu/
      url: https://www2.clarku.edu/faculty/facultybio.cfm?id=715
    - name: 
        given: Benjamin
        family: Runkle
        literal: Benjamin Runkle
      affiliations:
        - name: University of Arkansas
          url: https://www.uark.edu/
      url: https://engineering.uark.edu/directory/index/uid/brrunkle/name/Benjamin-Runkle/
    - name: William Anderegg
      url: https://faculty.utah.edu/u6003057-WILLIAM_ANDEREGG/research/index.hml
      affiliations:
        - name: University of Utah
          url: https://www.utah.edu/
    - name: Dave Hollinger
      url: https://www.fs.usda.gov/research/about/people/dhollinger
      affiliations:
        - name: USDA Forest Service
          url: https://www.fs.usda.gov/
    - name: Marcy Litvak
      url: https://biology.unm.edu/people/faculty/profile/litvak_marcy-e.html
      affiliations:
        - name: University of New Mexico
          url: https://www.unm.edu/
    - name: Caroline Normile
      url: https://bipartisanpolicy.org/person/caroline-normile/
      affiliations:
        - name: Bipartisan Policy Center
          url: https://bipartisanpolicy.org/
    - name: Gyami Shrestha
      affiliations: formerly US Carbon Cycle Science Program
    - name: Maya Almaraz 
      affiliations: Princeton University
    - name: Christa Anderson
      affiliations: World Wildlife Fund
    - name: Mallory Barnes
      affiliations: Indiana University
    - name: Dennis Baldocchi
      affiliations: University of California, Berkeley
    - name: Lily Colburn
      affiliations: U.S. Climate Alliance
    - name: Danny Cullenward
      affiliations: CarbonPlan
    - name: Margaret Evans
      affiliations: University of Arizona
    - name: Kaiyu Guan
      affiliations: University of Illinois
    - name: Trevor Keenan
      affiliations:
        - University of California, Berkeley
        - Lawrence Berkeley National Lab
    - name: Rachel Lamb
      affiliations: University of Maryland
    - name: Elizabeth Larson
      affiliations: North American Carbon Program
    - name: Emily Oldfield
      affiliations: Environmental Defense Fund
    - name: Benjamin Poulter
      affiliations: NASA
    - name: Julian Reyes
      affiliations: USDA Climate Hubs
    - name: Jonathan Sanderman
      affiliations: Woodwell Climate Research Center
    - name: Paul Selmants
      affiliations: USGS
    - name: Edil Sepulveda Carlo
      affiliations: NASA
    - name: Margaret Torn
      affiliations: Lawrence Berkeley National Lab
    - name: Anna Trugman
      affiliations: University of California, Santa Barbara
    - name: Christopher Woodall
      affiliations: USDA Forest Service

  date: "10/12/2022"
  language: en
  downloads: [pdf, epub]

  cover-image: img/front-cover.jpg
  cover-image-alt: "stream surrounded by grass and trees"

  chapters:
    - index.qmd
    - 01-overview-and-objectives.qmd
    - 02-knowledge-gaps.qmd
    - bibliography.qmd

  pdf-url: https://scholarworks.iu.edu/dspace/bitstream/handle/2022/28264/FullReport_20221011_uncoupled.pdf
  favicon: img/front-cover.jpg
  sharing: [twitter, facebook]
  twitter-card: 
    image: img/front-cover.jpg
    card-style: summary
  open-graph: true

  sidebar:
    logo: img/front-cover.jpg
    tools: 
      - icon: person
        href: https://oneill.indiana.edu/faculty-research/directory/profiles/faculty/full-time/novick-kimberly.html
      - icon: twitter
        href: https://twitter.com/iulibraries?lang=en
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.iu.edu/iusw/example-report
          - text: Report a Bug
            url:  https://github.iu.edu/iusw/example-report/issues


  # reader-mode: true

bibliography: references.bib
# site-url: https://pages.github.iu.edu/iusw/example-report/
# repo-url: https://github.iu.edu/iusw/example-report
# repo-actions: [edit]


citation:
  type: document
  publisher: Scholarly Communication Department, Indiana University Bloomington Libraries
  publisher-place: Bloomington, IN
  doi: "10.5967/n7r9-7j83"

google-scholar: true

format:
  html:
    theme: litera
    toc: true
    toc-title: Contents
    toc-expand: true
    number-sections: true
    anchor-sections: true
    smooth-scroll: true
    # link-external-icon: true
    link-external-newwindow: true
    comments:
      hypothesis: true
    keywords: example
    copyright: CC BY
  pdf:
    documentclass: scrreprt
    keep-tex: true
    font-family: libertinus
  epub:
    cover-image: img/front-cover.jpg